# Generated by Django 6.0.5 on 2026-06-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['email', 'timestamp'], name='api_loginat_email_eab493_idx'),
        ),
    ]
